$mainMod = SUPER # Sets "Windows" key as main modifier

# arrows
binde = $mainMod, P, sendshortcut, , up, activewindow
binde = $mainMod, L, sendshortcut, , left, activewindow
binde = $mainMod, semicolon, sendshortcut, , down, activewindow
binde = $mainMod, apostrophe, sendshortcut, , right, activewindow

# Ctrl + arrows
binde = $mainMod CTRL, P, sendshortcut, CTRL, up, activewindow
binde = $mainMod CTRL, L, sendshortcut, CTRL, left, activewindow
binde = $mainMod CTRL, semicolon, sendshortcut, CTRL, down, activewindow
binde = $mainMod CTRL, apostrophe, sendshortcut, CTRL, right, activewindow

# Shift + arrows
binde = $mainMod SHIFT, P, sendshortcut, SHIFT, up, activewindow
binde = $mainMod SHIFT, L, sendshortcut, SHIFT, left, activewindow
binde = $mainMod SHIFT, semicolon, sendshortcut, SHIFT, down, activewindow
binde = $mainMod SHIFT, apostrophe, sendshortcut, SHIFT, right, activewindow

# Ctrl + Shift + arrows
binde = $mainMod CTRL SHIFT, P, sendshortcut, CTRL SHIFT, up, activewindow
binde = $mainMod CTRL SHIFT, L, sendshortcut, CTRL SHIFT, left, activewindow
binde = $mainMod CTRL SHIFT, semicolon, sendshortcut, CTRL SHIFT, down, activewindow
binde = $mainMod CTRL SHIFT, apostrophe, sendshortcut, CTRL SHIFT, right, activewindow

# Left / Right -> Home / End
bind = $mainMod, left, sendshortcut, , home, activewindow
bind = $mainMod, right, sendshortcut, , end, activewindow

# up / down -> home / end
bind = $mainMod, up, sendshortcut, CTRL, home, activewindow
bind = $mainMod, down, sendshortcut, CTRL, end, activewindow

# Shift + Left / Right -> Shift + Home / Shift + End
bind = $mainMod SHIFT, left, sendshortcut, SHIFT, home, activewindow
bind = $mainMod SHIFT, right, sendshortcut, SHIFT, end, activewindow

# Shift + Up / Down -> Ctrl + Shift + Home / Ctrl + Shift + End
bind = $mainMod SHIFT, up, sendshortcut, CTRL SHIFT, home, activewindow
bind = $mainMod SHIFT, down, sendshortcut, CTRL SHIFT, end, activewindow
