$mainMod = SUPER # Sets "Windows" key as main modifier

# new arrows
binde = $mainMod, P, sendshortcut, , up, activewindow
binde = $mainMod, L, sendshortcut, , left, activewindow
binde = $mainMod, semicolon, sendshortcut, , down, activewindow
binde = $mainMod, apostrophe, sendshortcut, , right, activewindow

# Ctrl + new arrows
binde = $mainMod CTRL, P, sendshortcut, CTRL, up, activewindow/
binde = $mainMod CTRL, L, sendshortcut, CTRL, left, activewindow
binde = $mainMod CTRL, semicolon, sendshortcut, CTRL, down, activewindow
binde = $mainMod CTRL, apostrophe, sendshortcut, CTRL, right, activewindow

# Shift + new arrows
binde = $mainMod SHIFT, P, sendshortcut, SHIFT, up, activewindow
binde = $mainMod SHIFT, L, sendshortcut, SHIFT, left, activewindow
binde = $mainMod SHIFT, semicolon, sendshortcut, SHIFT, down, activewindow
binde = $mainMod SHIFT, apostrophe, sendshortcut, SHIFT, right, activewindow

# Ctrl + Shift + new arrows
binde = $mainMod CTRL SHIFT, P, sendshortcut, CTRL SHIFT, up, activewindow
binde = $mainMod CTRL SHIFT, L, sendshortcut, CTRL SHIFT, left, activewindow
binde = $mainMod CTRL SHIFT, semicolon, sendshortcut, CTRL SHIFT, down, activewindow
binde = $mainMod CTRL SHIFT, apostrophe, sendshortcut, CTRL SHIFT, right, activewindow

# O / ]-> Home / End
bind = $mainMod, O, sendshortcut, , home, activewindow
bind = $mainMod, bracketleft, sendshortcut, , end, activewindow

# up / down -> home / end
bind = $mainMod, up, sendshortcut, CTRL, home, activewindow
bind = $mainMod, down, sendshortcut, CTRL, end, activewindow

# Shift + Left / Right -> Shift + Home / Shift + End
bind = $mainMod SHIFT, O, sendshortcut, SHIFT, home, activewindow
bind = $mainMod SHIFT, bracketleft, sendshortcut, SHIFT, end, activewindow

# CTRL + Shift + Left / Right -> Shift + Home / Shift + End
bind = $mainMod CTRL SHIFT, O, sendshortcut, SHIFT, home, activewindow
bind = $mainMod CTRL SHIFT, bracketleft, sendshortcut, SHIFT, end, activewindow

# Shift + Up / Down -> Ctrl + Shift + Home / Ctrl + Shift + End
bind = $mainMod SHIFT, up, sendshortcut, CTRL SHIFT, home, activewindow
bind = $mainMod SHIFT, down, sendshortcut, CTRL SHIFT, end, activewindow

# CTRL + Shift + Up / Down -> Ctrl + Shift + Home / Ctrl + Shift + End
bind = $mainMod CTRL SHIFT, up, sendshortcut, CTRL SHIFT, home, activewindow
bind = $mainMod CTRL SHIFT, down, sendshortcut, CTRL SHIFT, end, activewindow

binde = ALT, P, sendshortcut, ALT, up, activewindow
binde = ALT, L, sendshortcut, ALT, left, activewindow
binde = ALT, semicolon, sendshortcut, ALT, down, activewindow
binde = ALT, apostrophe, sendshortcut, ALT, right, activewindow
